server: add convenient eval
tarantool/luatest pull request #144
Opened 2021-07-14 09:17 UTC by VitaliyaIoffe

Syntactic sugar for using net_box eval

What has been done? Why? What problem is being solved?

I didn't forget about

- [ ] Tests
- [ ] Changelog
- [ ] Documentation

Close #???

2021-07-14 18:56 UTC, Steap2448 requested changes
Thanks for your patch! Consider the following comments.

2021-07-14 18:56 UTC, Steap2448 commented on luatest/server.lua
> +function Server:eval(command)
Arguments and options should be passed as well. See doc [here](https://www.tarantool.io/en/doc/latest/reference/reference_lua/net_box/#lua-function.conn.eval).

2021-07-14 18:56 UTC, Steap2448 commented on luatest/server.lua
> +    return self.net_box:eval(command)
```suggestion
function Server:eval(command)
    assert(self.net_box, 'net_box is not connected')
    return self.net_box:eval(command)
```

2021-07-14 18:56 UTC, Steap2448 commented on luatest/server.lua
> +
Consider adding a corresponding function for `net_box:call`.

2021-07-14 20:55 UTC, rosik commented on luatest/server.lua
> +    return self.net_box:eval(command)
```suggestion
function Server:eval(...)
    assert(self.net_box, 'net_box is not connected')
    return self.net_box:eval(...)

2021-07-14 21:01 UTC, rosik commented
I like the idea. Please, make use of the new function:

```console
$ grep -Rn 'net_box:eval'
README.rst:280:    server.net_box:eval('return do_something(...)', {arg1, arg2})
luatest/server.lua:212:    self.net_box:eval('require("luatest.coverage_utils").' .. action .. '()')
test/server_test.lua:111:    t.assert_equals(server.net_box:eval('return os.getenv("custom_env")'), 'test_value')
```

2021-07-15 07:58 UTC, VitaliyaIoffe commented on luatest/server.lua
> +    return self.net_box:eval(command)
Thank you! Fixed

2021-07-15 11:06 UTC, Steap2448 approved these changes
Nice one!

2021-07-15 11:51 UTC, rosik approved these changes

2021-07-15 14:21 UTC, merged